name: documentation

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6  # docs: https://github.com/marketplace/actions/checkout
      - uses: astral-sh/setup-uv@v6  # docs: https://github.com/marketplace/actions/astral-sh-setup-uv
        with:
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --locked --group docs
      - name: (Debug) Dump environment details
        run: |
          echo "VIRTUAL_ENV    : ${VIRTUAL_ENV}"
          echo "CONDA_PREFIX   : ${CONDA_PREFIX}"
          echo "Python path    : $(uv python find)"
          echo "Python version : $(uv run python --version)"
          echo "Python package versions:"
          uv pip freeze
      - name: Sphinx build
        run: uv run sphinx-build -v docs build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          force_orphan: true
